[package]
name = "quote_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
reqwest = { version = "0.11", features = ["blocking"] }
json = "0.12.4"
